#!/bin/sh
echo ${PWD##*/} > Rapport/hierarchie.txt
tree --charset ascii --prune -I $(cat .gitignore .gitignore | egrep -v "^#.*$|^[[:space:]]*$" | tr "\\n" "|") >> Rapport/hierarchie.txt
mkdir ../rendu/
cd ../rendu/
cp --parents $(git ls-files --full-name | tr " " "\\_") ./
rm -r $(cat ../l3-rvc/.ignore_rendu)

