#!/bin/sh
echo ${PWD##*/} > rapport/hierarchie.txt
tree --charset ascii --prune -I $(cat .gitignore .ignore_rendu .gitignore | egrep -v "^#.*$|^[[:space:]]*$" | tr "\\n" "|") >> rapport/hierarchie.txt
mkdir ../rendu/
cp --parents $(git ls-files --full-name | tr " " "\\_") ../rendu/
cd ../rendu/
rm -r $(cat ../l3-rvc/.ignore_rendu)
