#!/bin/sh
echo ${PWD##*/} > Rapport/hierarchie.txt
tree --charset ascii --prune -I $(cat .gitignore .gitignore | egrep -v "^#.*$|^[[:space:]]*$" | tr "\\n" "|") >> Rapport/hierarchie.txt
mkdir ../rendu/
git ls-files --full-name | tr "\ " "\\ " > Rapport/rendu/index.txt
cp --parents $(git ls-files --full-name | tr " " "\\ ") ../rendu/

